### PR TITLE
solving this issue https://github.com/DaKaZ/esp8266-restclient/issues/3

### PR DESCRIPTION
**Pull request by ccfiel**

### CODE REVIEW

**Comment by DaKaZ** [comment]
Hi @ccfiel and thanks for the PR.  I have a few questions. I think the original issue suggests a user would need to pass in both the IP address and the desired host header. I have not tested your code but I don’t think it does anything functionally different since you are just pulling the IP address from the host name.  I also think the original issues requires us to use the host header in the HTTP requests. I am certainly open to accepting a PR that fully addresses that issue, I just don’t think this one does that. Let me know if my brief analysis is off. Thanks again for the PR though, it’s always better to have more contributors!

**Comment by ccfiel** [comment]
Hello @DaKaZ actually we have the same issue this is
my old code.
```  WiFiClientSecure client;
  const int httpPort = 443;
  IPAddress remote_addr;
  WiFi.hostByName(metromatik_url, remote_addr);
  if (!client.connect(remote_addr, httpPort)) {
    Serial.println("connection failed");
    return false;
  }

  if (client.verify(fingerprint, metromatik_url)) {
    Serial.println("certificate matches");
  } else {
    Serial.println("certificate doesn't match");
  }

  String url = "/api/method/metromatik.rest.reading";
  String data = "{\"id\": " + String(ESP.getChipId()) + ", \"force\": " + String(force) + ", \"value\": " + String(kilo_watt) + ", \"kind\": \"E\"}";
  client.println("POST " + url + " HTTP/1.1");
  client.println("Host: " + String(metromatik_url));
  client.println("Accept: */*");
  client.println("Content-Type: application/json");
  client.print("Content-Length: ");
  client.println(data.length());
  client.println();
  client.print(data);
```
Using your library with my PR

```
  RestClient client = RestClient(metromatik_url, 443, "EE 16 77 79 55 58 92 46 FB 18 40 99 2E 17 7E AB 32 0A 4A 88");
  String response = "";
  String data = "{\"id\": " + String(ESP.getChipId()) + ", \"force\": " + String(force) + ", \"value\": " + String(kilo_watt) + ", \"kind\": \"E\"}";
  char request[800];
  data.toCharArray(request, 800);
  client.setHeader("Host: 1220.metromatik.com");
  client.setHeader("Accept: */*");
  client.setContentType("Content-Type: application/json");

  int statusCode = client.post("/api/method/metromatik.rest.reading", request, &response);

```
Yes you are correct. If you just pass the domain name not the IP. The server will return an error. 
To make your library work in this scenario 
1. Get the IP of the domain name and use it in the connect
2. Add header Host ex.
    ```
  client.setHeader("Host: 1220.metromatik.com");
```

I hope this will answer your question. :)

**Comment by DaKaZ** [comment]
I just looked at this again, the only reason this works is the removal of line 171, which makes the client not secure at all.  If the certs don't match, we should stop execution.   I think the issue is the use of a subjectAltName in the cert which ssl client library simply doesn't support.  I could be wrong, but thats what I am seeing.

**Comment by DaKaZ** [comment]
Closing this for now... please re-open an issue/pr if you're still having a problem

**Pull request closed without merging**
